version: '3.8'

services:
  phpnuxbill:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PHPNuxBill
    depends_on:
      - mysql
    ports:
      - "8787:80"
      - "8743:443"
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: phpnuxbill
    volumes:
      - phpnuxbill_data:/var/www/html
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phpnuxbill
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  phpnuxbill_data:
  mysql_data:
