version: '3.8'

services:
  phpnuxbill:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpnuxbill
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
