[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/apache2.log
stderr_logfile=/var/log/supervisor/apache2_err.log

[program:freeradius]
command=/usr/sbin/freeradius -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/freeradius.log
stderr_logfile=/var/log/supervisor/freeradius_err.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/cron.log
stderr_logfile=/var/log/supervisor/cron_err.log
