[supervisord]
nodaemon=true

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
autostart=true
autorestart=true

[program:freeradius]
command=/usr/sbin/freeradius -f
autostart=true
autorestart=true
